spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop-web
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernats:
        format-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

